version: '3.8'
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports: 
      - "3000:3000"
    depends_on:
      - server


  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/myapp
      - PORT=5000
    volumes:
      - ./server:/app
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:
